### ISSUE TITLE
Route, Map

### ISSUE THREAD

**Issue by rmstaanaIT** [prafullmishra/Guide-for-NMRC#1]
Hi, how to customize the map and route and generate the json files in assets? Would appreciate your help, thanks!

**Comment by prafullmishra** [comment]
Map was custom creating using illustration tools such as Inkscape, Adobe Illustrator. The coordinates of the points on map were then mapped manually in the JSON. It would need to be custom written for a different implementation.

**Comment by rmstaanaIT** [comment]
Where can I map the points to produce a custom json file? Thank you
